import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Water Wise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <div className="flex flex-col items-center h-full w-[300px] bg-white">
            <img src="./favicon.ico" alt="" />
            <nav>
              <ul className="flex flex-col items-center text-blue-500">
                <Link href={'/'}><li>HOME</li></Link>
                <Link href={'/dams'}><li>DAMS PAGE</li></Link>
              </ul>
            </nav>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
